# Generated by Django 2.2.7 on 2019-11-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191112_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.CharField(blank=True, default='人生苦短，我用Python', max_length=50, null=True, verbose_name='个性签名'),
        ),
    ]
