# Generated by Django 2.2.7 on 2019-11-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191109_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebanner',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='标题'),
        ),
    ]
