# Generated by Django 2.2.7 on 2019-11-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailverifyrecord_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
