# Generated by Django 2.2.7 on 2019-11-18 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191118_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='生日'),
        ),
    ]
