# Generated by Django 2.2.7 on 2019-11-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='courses/%Y/m'),
        ),
    ]
