# Generated by Django 2.1.4 on 2019-04-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_aritical_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aritical',
            new_name='Article',
        ),
    ]
