# Generated by Django 2.1.4 on 2019-04-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20190426_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='createtime',
            field=models.DateField(auto_now=True),
        ),
    ]
