# Generated by Django 2.2.7 on 2020-01-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191211_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='  ', verbose_name='轮播图片'),
        ),
    ]
