# Generated by Django 2.2 on 2020-01-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20200113_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, editable=False, max_length=100, null=True, unique=True,
                                    verbose_name='邮箱'),
        )
    ]
