# Generated by Django 2.2.7 on 2019-11-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地址')),
                ('message', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='留言内容')),
            ],
            options={
                'verbose_name': '留言信息',
                'verbose_name_plural': '留言信息',
            },
        ),
    ]
