# Generated by Django 2.2.7 on 2019-12-27 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('done', models.BooleanField(default=False, verbose_name='完成情况')),
                ('link', models.CharField(max_length=50, verbose_name='文章链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章清单',
                'verbose_name_plural': '文章清单',
            },
        ),
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='网站标题')),
                ('type', models.IntegerField(choices=[(1, '博客'), (2, '论坛'), (3, '资源')], default=1, verbose_name='网站类型')),
                ('link', models.CharField(max_length=50, verbose_name='网站链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '网址导航',
                'verbose_name_plural': '网址导航',
            },
        ),
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='目标内容')),
                ('type', models.IntegerField(choices=[(1, '周目标'), (2, '月目标'), (3, '年目标')], default=1, verbose_name='目标类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='ThingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='事项名称')),
                ('done', models.BooleanField(default=False, verbose_name='完成情况')),
                ('level', models.IntegerField(choices=[(1, '一般'), (2, '紧急')], default=1, verbose_name='紧急程度')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '代办事项',
                'verbose_name_plural': '代办事项',
            },
        ),
    ]
