# Generated by Django 2.2.7 on 2019-12-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0002_auto_20191227_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetmodel',
            options={'verbose_name': '个人目标', 'verbose_name_plural': '个人目标'},
        ),
    ]
