# Generated by Django 2.2.7 on 2020-01-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0004_auto_20200102_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='type',
            field=models.IntegerField(choices=[(1, '博客类'), (2, '论坛类'), (3, '资源类')], default=1, verbose_name='网站类型'),
        ),
    ]
